// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package easyexcel.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.Date;
import java.util.List;
import com.alibaba.excel.EasyExcel;
import com.alibaba.excel.util.ListUtils;

public class Java_action_export extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String app_id;

	public Java_action_export(IContext context, java.lang.String app_id)
	{
		super(context);
		this.app_id = app_id;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		// 方案1 根据对象填充
		String fileName = System.currentTimeMillis() + ".xlsx";
		EasyExcel.write(fileName).head(head()).sheet("模板").doWrite(dataList());
		return null;
		// throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action
		// was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action_export";
	}

	// BEGIN EXTRA CODE
	private List<List<String>> head() {
		List<List<String>> list = ListUtils.newArrayList();
		List<String> head0 = ListUtils.newArrayList();
		head0.add("字符串" + System.currentTimeMillis());
		List<String> head1 = ListUtils.newArrayList();
		head1.add("数字" + System.currentTimeMillis());
		List<String> head2 = ListUtils.newArrayList();
		head2.add("日期" + System.currentTimeMillis());
		list.add(head0);
		list.add(head1);
		list.add(head2);
		return list;
	}

	private List<List<Object>> dataList() {
		List<List<Object>> list = ListUtils.newArrayList();
		for (int i = 0; i < 10; i++) {
			List<Object> data = ListUtils.newArrayList();
			data.add("字符串" + i);
			data.add(new Date());
			data.add(0.56);
			list.add(data);
		}
		return list;
	}
	// END EXTRA CODE
}
